# Generated by Django 2.2.5 on 2019-11-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
